### PR TITLE
GH-145 Use arch_linux compatible time formatting

### LINKED ISSUE #145: [Linux] Can't open Project with Orchestrator
### Describe the bug

After installing the plugin into any (old or fresh) godot project.
The project can't be opened anymore after enabling the plugin on Linux.

### Expected behavior

- The project opens with the plugin is enabled

### Actual behavior

- The Editor crashes during project loading

### How to Reproduce?

PreConditions:
- Operating System: Linux (Arch)
- Godot 4.2.1 (Installation from Official Arch Extra Repo - No AUR - No Flatpak)
- Godot-Orchestrator-v2.0-dev3-plugin

1. Open Godot 4.2.1 Project Explorer
2. Create a new project
3. Close the Project
4. Open File Explorer and copy the plugins addon folder into the project
5. Open Godot 4.2.1 Project Explorer
6. Open the project
7. Click on Restart
8. Editor Crashes

### Godot full version

4.2.1

### Orchestrator version

v2.0-dev3-plugin

### Additional information

```
Godot Engine v4.2.1.stable.arch_linux - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 550.54.14 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1080
 
Editing project: /home/<USER>/Projects/Godot Projects/vstest

================================================================
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.1.stable.arch_linux
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /usr/lib/libc.so.6(+0x3c770) [0x78602c352770] (??:0)
[2] std::__codecvt_utf16_base<char16_t>::do_unshift(__mbstate_t&, char*, char*, char*&) const (??:0)
[3] std::ostream& std::ostream::_M_insert<long>(long) (??:0)
[4] void Logger::_log<char const (&) [41]>(Logger::Level, char const (&) [41]) (??:0)
[5] orchestrator::initialize_extension_module(godot::ModuleInitializationLevel) (??:0)
[6] godot::GDExtensionBinding::initialize_level(void*, GDExtensionInitializationLevel) (??:0)
[7] /usr/bin/godot(+0x3d46493) [0x5bac2d66e493] (??:?)
[8] /usr/bin/godot(+0x405c5a4) [0x5bac2d9845a4] (??:?)
[9] /usr/bin/godot(+0x582f12) [0x5bac29eaaf12] (??:?)
[10] /usr/lib/libc.so.6(+0x25cd0) [0x78602c33bcd0] (??:0)
[11] /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x78602c33bd8a] (??:0)
[12] /usr/bin/godot(+0x58fda5) [0x5bac29eb7da5] (??:?)
-- END OF BACKTRACE --
================================================================
```

### PR DESCRIPTION
**Pull request by Naros**
Fixes #145

### CODE REVIEW

File: src/common/logger.h [hunk 1]
```diff
@@ -104,16 +104,14 @@ class Logger
...
-            ss << year << '-' << std::setw(2) << month << '-' << std::setw(2) << day;
-            ss << ' ';
-            ss << std::setw(2) << hours << ':' << std::setw(2) << minutes << ':' << std::setw(2) << seconds;
-
-            const String timestamp = ss.str().c_str();
+            char buffer[256];
+            #ifndef _WIN32
+            sprintf(buffer, "%04d-%02d-%02d %02d:%02d:%02d", year, month, day, hours, minutes, seconds);
+            #else
+            sprintf_s(buffer, 256, "%04d-%02d-%02d %02d:%02d:%02d", year, month, day, hours, minutes, seconds);
```
Comment (TomCoursow) [inline src/common/logger.h:111]: My C/C++ knowledge is limited (was my first programming language but nowerdays I use it rather seldom as since I work as a software dev I always developed java server applications)
But if buffering was the issue, would it also be possible to use snprintf insetad to save the operating system check?

Like:
```
...
int minutes = local_tm.tm_min;
int seconds = local_tm.tm_sec;

char buffer[256];
snprintf(buffer, sizeof(buffer), "%04d-%02d-%02d %02d:%02d:%02d", year, month, day, hours, minutes, seconds);

String message = buffer;
message += " [" + _get_level(p_level) + "]: ";

...
```

Comment (Naros) [reply src/common/logger.h:111]: Yep, I'll make that adjustment 👍
